import { Food } from "./index";

export const FoodModel: Food[] = [
  {
    images: "https://online-foods.herokuapp.com/images/chicken_dry.jpg",
    _id: "5ec01c2c6b0ad806dd79c3e1",
    name: "Chiken Dry",
    description: "Chichen Crispy Fry",
    category: "Starter",
    price: 156,
    readyTime: 30,
  },
  {
    images: "https://online-foods.herokuapp.com/images/chicken_afgan.jpg",
    _id: "5ec0c70d43434c07314cdf5f",
    name: "Chicken Afgan",
    description: "Afgani flavor with Green Leafy vegetable",
    category: "Starter",
    price: 345,
    readyTime: 30,
  },
  {
    images: "https://online-foods.herokuapp.com/images/chicken_indi.jpg",
    _id: "5ec0c75443434c07314cdf60",
    name: "Chicken Indie",
    description: "Complete Chicken with Garlic and hot Spice Roast",
    category: "Main",
    price: 345,
    readyTime: 30,
  },
  {
    images: "https://online-foods.herokuapp.com/images/chicken_lolipop.jpeg",
    _id: "5ec0c76743434c07314cdf61",
    name: "Chicken Lollipop",
    description: "Chicken Lollipop with Garlic and hot Spice",
    category: "Main",
    price: 267,
    readyTime: 30,
  },
  {
    images: "https://online-foods.herokuapp.com/images/chicken_roast.jpg",
    _id: "5ec0c77a43434c07314cdf63",
    name: "Chicken Roast",
    description: "Roast Chicken aroma flavor with Green Leafy vegetable",
    category: "Starter",
    price: 300,
    readyTime: 45,
  },
  {
    images: "https://online-foods.herokuapp.com/images/fried_rice.jpg",
    _id: "5ec0c7b943434c07314cdf64",
    name: "Fried Rice with Green Chutny",
    description: "Great quality of Fried Rice with Green Chutny",
    category: "Break-fast",
    price: 160,
    readyTime: 25,
  },
  {
    images: "https://online-foods.herokuapp.com/images/light_break_fast.jpg",
    _id: "5ec0c80043434c07314cdf66",
    name: "Butter Bread Sandwich Light",
    description: "Light Breakfast & Bread with Cheezy flavor toping",
    category: "Break-fast",
    price: 220,
    readyTime: 20,
  },
  {
    images: "https://online-foods.herokuapp.com/images/bread_sandwich.jpg",
    _id: "5ec0c81343434c07314cdf67",
    name: "Butter Bread Sandwich",
    description: "Machka Bread with Cheezy flavor",
    category: "Break-fast",
    price: 210,
    readyTime: 30,
  },
  {
    images: "https://online-foods.herokuapp.com/images/rice_veg_bowl.jpeg",
    _id: "5ec0c82743434c07314cdf69",
    name: "Rice Veg Bowl",
    description: "Great quality of Rice with Healthy flavor Ingredients",
    category: "Break-fast",
    price: 110,
    readyTime: 30,
  },
];
